[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
riscv = "0.15"
driver-uart = { path = "../drivers/uart" }
fdt = "0.1.5"
spin = "0.10.0"

[build-dependencies]
cc = "1.2.38"

[features]
default = []
tests = []
